if !File.exist?(".env")
    puts "Inception-Of-Things: ERROR: .env file does not exist"
    exit
end

File.open(".env", "r") do |f|
    f.each_line do |line|
        if line =~ /^K3S_TOKEN/
            ENV["K3S_TOKEN"] = line.split("=")[1].strip
        end
    end
    if !ENV["K3S_TOKEN"]
        puts "Inception-Of-Things: ERROR: K3S_TOKEN not found in .env file"
        exit
    end
end

Vagrant.configure("2") do |config|
    config.vm.box = "generic/alpine317"
    config.vm.define "darodrigS" do |server|
        server.vm.hostname = "darodrigS"
        server.vm.network "private_network", ip: "192.168.56.110"
        server.vm.provider "virtualbox" do |v|
            v.name = "darodrigS"
            v.memory = 2048
            v.cpus = 1
            v.gui = false
        end
        server.vm.synced_folder ".", "/vagrant"
        server.vm.provision :shell ,privileged: true,  path: "scripts/provision.sh" 
        server.vm.provision :shell, privileged: true, path: "scripts/up.sh" 
    end
end